name: gptsam-local
services:
  app:
    build: ..
    image: gptsam-app:v1
    container_name: app
    depends_on:
      mysql:
        condition: service_healthy
    env_file:
      - .env.local
    ports:
      - "8080:8080"

  mysql:
    image: mysql:8.4.4
    container_name: mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 2s
      timeout: 2s
      retries: 10
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD_LOCAL}
      MYSQL_DATABASE: ${DB_NAME_LOCAL}
    ports:
      - "23306:3306"
