name: gptsam-dev
services:
  app:
    image: ${DOCKERHUB_USERNAME}/gptsam-app:dev
    container_name: app
    depends_on:
      mysql:
        condition: service_healthy
    env_file:
      - .env.dev
    volumes:
      - /home/ubuntu/gptsam/backend/app/dev/logs:/app/dev/logs
    ports:
      - "8080:8080"

  mysql:
    image: mysql:8.4.4
    container_name: mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 5s
      timeout: 5s
      retries: 10
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD_DEV}
      MYSQL_DATABASE: ${DB_NAME_DEV}
      MYSQL_ROOT_HOST: "%"
    ports:
      - "23306:3306"
