server:
  port: 8080
  base-url: http://localhost:8080
cors:
  allowed-origins: http://localhost:3000
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL_LOCAL}
    username: ${DB_USERNAME_LOCAL}
    password: ${DB_PASSWORD_LOCAL}
