server:
  port: 8080
  base-url: http://localhost:8080
cors:
  allowed-origins: http://localhost:3000
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL_LOCAL}
    username: ${DB_USERNAME_LOCAL}
    password: ${DB_PASSWORD_LOCAL}
security:
  jwt:
    secret-key: ${SERVER_LOCAL_JWT_SECRET_KEY}
    expiration-ms: 60000           # 1분; 1000 * 60
    refresh-expiration-ms: 300000  # 5분; 1000 * 60 * 5
  cookie:
    max-age: 300         # 초 단위, 5분
    is-secure: false     # HTTPS 사용여부, 프로덕션 시 true
    http-only: true
    same-site: "Strict"  # [None | Lax | Strict]
